version: 2

sources:
  - name: gz_raw_data
    database: alejacantik2
    schema: gz_raw_data
    loader: bigquery
    description: raw data from gz
    
    tables:
      - name: raw_gz_sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        loaded_at_field: date_date
        freshness: 
          error_after:
            count: 90
            period: day
        
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: id of the order
           - name: products_id
             description: product id
           - name: revenue
             description: revenue per order 
        tests:
             - unique:
                 column_name: "(orders_id || '-' || pdt_id)"
      - name: raw_gz_product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
            - name: products_id
              description: product id
              tests:
                - not_null
                - unique
            - name: purchase_price
              description: purchase price

      - name: raw_gz_ship
        identifier: raw_gz_ship
        description: shipment info of Greenweez 
        columns:
            - name: orders_id
              description: order id
              tests:
                - not_null
                - unique
            - name: shipping_fee
              description: shipping fee
            - name: logCost
              description: cost of logistic
            - name: ship_cost
              description: shipping cost