version: 2

sources:
   - name: gz_raw_data
     database: alejacantik2
     schema: gz_raw_data
     loader: bigquery
     description: raw data from gz
     freshness:
       warn_after: {count: 12, period: hour}
       error_after: {count: 24, period: hour}
     tables:
       - name: raw_gz_sales
       - name: raw_gz_product
       - name: raw_gz_ship